---
title: "Group Experiments: Homogenous Members"
author: "Ali Seyhun Saral"
date: "25 Nov 2021"
output: 
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightLines: true
      highlightStyle: github
      countIncrementalSlides: false
  
---
```{css, echo=FALSE}
.remark-code, .remark-inline-code {
  font-size: 80%;
  color: blue;
	background-color: rgba(222,222,222,0.3);
}
.titletext {
	font-size: 400%;
  display:inline-block; 
}

.smaller {
	font-size: 70%;
  display:inline-block; 
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::knit_engines$set(htmlrun = function(options) {
  print(options$code)
  # the source code is in options$code; just do
  # whatever you want with it
})
```
## Individual Experiments
* We have covered individual experiments so far.

--

* Create `Player` fields for the variables written in the data

--

* Create `Pages` for each page we will see and add fields with `form_fields`

--

* Create/modify the templates for each page. (`PageName.html`, `AnotherPage.html`)

---

## Group Experiments I - Homogenous Groups
* **Homogenous Groups** 

  * All members have the same role.
  
  * They see the same pages.

--


<br><br><br>

* Some technical aspects differ from the individual experiments:

| Aspect                     | Individual Task        | Group Task                                     |
| -----------------          | ------------------     | --------                                       |
| **Variables / Calculations** | My own variables   | Need to reach other players' variables        |
| **Pages**                  | My own pace | Sometimes have to wait for others|

---

## oTree models
**`__init__.py`**:
```{python, eval=FALSE}
# MODELS
class Constants(BaseConstants):
    name_in_url = 'my_survey'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    some_individual_variable = models.IntegerField()
```

---
# Models
* They are managing objects which represent players/groups/the constants and handle database entries.
--

* Four built-in models:
  * `Player`: Parameters that are unique for each individual.
  
  * `Group` : Parameters that are unique for the group, same for each individual in the group.
  
  * `Constants`: Parameters that are the same for the experiment.
     * Beware:Constants are not written on the data!
  
  * `Subsession`: Parameters that are same for the "subsession". More often used to initiate some specific settings. We will see it next week.
---

## Setting group size

* Groups structure is created and handled automatically by oTree

```{python, eval=FALSE}
class Constants(BaseConstants):
    # ...
    players_per_group = 3
    # ...
    
```
---






# Creating Fields in our models

| Variable          |  Field Type      |
|-------------------|------------------|
| `name`            | `StringField`    |
| `age`             | `IntegerField`   | 
| `mood`            | `StringField`    |
| `wants_feedback`  | `BooleanField`   |
| `comments`        | `LongStringField`|


---

# Creating Pages

| Page                |  Description      |
|---------------------|-------------------|
| `Survey`            |  Survey questions |
| `Results`           |  Feedback         |

* Each page will have a 

--

  * Class in `__init__.py` 
  
--

  * They should be added to `page_sequence` list
  
--

  * Will have a `html` template in the same folder

---
